version: 1.0.{build}
clone_depth: 50

branches:
  only:
    - master

skip_commits:
  files:
    - README.md
    - .appveyor.yml
    - .travis.yml
    
only_commits:
  files:
    - src/**

# Operating system (build VM template)
os: Visual Studio 2017

# Build platform, i.e. x86, x64, AnyCPU. This setting is optional.
platform:
  - x86
#  - x64

# build Configuration, i.e. Debug, Release, etc.
configuration:
#  - Debug
  - Release

matrix:
  # The build fail immediately once one of the job fails
  fast_finish: true

# Scripts that are called at very beginning, before repo cloning
init:
  - cmake --version
  - msbuild /version

build_script: 
  - mkdir build
  - cd build
  - cmake c:\projects\iathena\src -G "Visual Studio 15"
  - cmake --build .
  
